FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-stretch-run

ENV INITSYSTEM on

COPY content/ /

RUN apt-get update \
 && apt-get install -yq \
 apt-transport-https \
 apt-utils \
 build-essential \
 curl \
 cron \
 i2c-tools \
 fping \
 nano \
 lldpd \
 lighttpd \
 python-pip \
 python-dev \
 python3-dev \
 python3-pip \
 python3-rpi.gpio \
 python3-smbus \
 supervisor \
 wget \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

CMD ["bash", "/opt/start.sh"]
