#!/bin/bash


/etc/init.d/lighttpd start

# Allow any signal which would kill a process to stop server
trap "service lighttpd stop" HUP INT QUIT ABRT ALRM TERM TSTP

while pgrep -u root lighttpd > /dev/null; do sleep 5; done
